language: java
jdk:
    - openjdk8
before_script:
    - echo "MAVEN_OPTS='-Xmx1g'" > ~/.mavenrc
    - git clone https://github.com/doudouchat/exemple-service.git /tmp/exemple-service
    - git clone https://github.com/doudouchat/exemple-authorization.git /tmp/exemple-authorization
    - mvn -f /tmp/exemple-service clean install -Dmaven.test.skip=true
    - mvn -f /tmp/exemple-authorization -s .travis.settings.xml clean install -Dmaven.test.skip=true
script: mvn -s .travis.settings.xml verify -Pwebservice,it
install: true
sudo: false
cache:
    directories:
        - $HOME/.m2