language: java
jdk:
    - openjdk8
before_script:
    - echo "MAVEN_OPTS='-Xmx1g'" > ~/.mavenrc
    - git clone https://github.com/doudouchat/exemple-service.git /tmp/exemple-service
    - git clone https://github.com/doudouchat/exemple-authorization.git /tmp/exemple-authorization
    - mvn -f /tmp/exemple-service clean source:aggregate install install:install-file -Dfile=/tmp/exemple-service/target/exemple-service-1.0.2-SNAPSHOT-sources.jar -DgroupId=exemple -DartifactId=exemple-service -Dpackaging=jar -Dversion=1.0.2-SNAPSHOT -Dclassifier=sources -Dmaven.test.skip=true
    - mvn -f /tmp/exemple-authorization -s .travis.settings.xml clean source:aggregate install install:install-file -Dfile=/tmp/exemple-authorization/target/exemple-authorization-1.0.1-SNAPSHOT-sources.jar -DgroupId=exemple -DartifactId=exemple-authorization -Dpackaging=jar -Dversion=1.0.1-SNAPSHOT -Dclassifier=sources -Dmaven.test.skip=true
script: mvn -s .travis.settings.xml verify -Pwebservice,it
after_success:
    - bash <(curl -s https://codecov.io/bash)
install: true
sudo: false
cache:
    directories:
        - $HOME/.m2